-- Copyright The OpenTelemetry Authors
-- SPDX-License-Identifier: Apache-2.0

-- Enable legacy mode to create users without C## prefix in CDB
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Create user (Oracle syntax)
CREATE USER otelu IDENTIFIED BY otelp;
GRANT CONNECT, RESOURCE TO otelu;
GRANT CREATE SESSION TO otelu;
GRANT UNLIMITED TABLESPACE TO otelu;

-- Commit user creation to ensure it persists
COMMIT;

-- Create Instana monitoring role
CREATE ROLE INSTANAROLE;

-- Grant privileges to Instana role for monitoring views
GRANT SELECT ON V_$SESSION TO INSTANAROLE;
GRANT SELECT ON V_$BGPROCESS TO INSTANAROLE;
GRANT SELECT ON V_$ACTIVE_SESSION_HISTORY TO INSTANAROLE;
GRANT SELECT ON V_$SYSSTAT TO INSTANAROLE;
GRANT SELECT ON V_$SGASTAT TO INSTANAROLE;
GRANT SELECT ON V_$LIBRARYCACHE TO INSTANAROLE;
GRANT SELECT ON V_$LATCH TO INSTANAROLE;
GRANT SELECT ON V_$ROWCACHE TO INSTANAROLE;
GRANT SELECT ON V_$STATNAME TO INSTANAROLE;
GRANT SELECT ON V_$SESSTAT TO INSTANAROLE;
GRANT SELECT ON V_$PROCESS TO INSTANAROLE;
GRANT SELECT ON V_$SQLAREA TO INSTANAROLE;
GRANT SELECT ON V_$PARAMETER TO INSTANAROLE;
GRANT SELECT ON V_$SQL TO INSTANAROLE;
GRANT SELECT ON V_$VERSION TO INSTANAROLE;
GRANT SELECT ON V_$RESOURCE_LIMIT TO INSTANAROLE;
GRANT SELECT ON V_$SYS_TIME_MODEL TO INSTANAROLE;
GRANT SELECT ON V_$SYSTEM_WAIT_CLASS TO INSTANAROLE;
GRANT SELECT ON V_$INSTANCE TO INSTANAROLE;
GRANT SELECT ON V_$LOCK TO INSTANAROLE;
GRANT SELECT ON DBA_HIST_SQLTEXT TO INSTANAROLE;
GRANT SELECT ON DBA_HIST_SQLSTAT TO INSTANAROLE;
GRANT SELECT ON DBA_HIST_SNAPSHOT TO INSTANAROLE;
GRANT SELECT ON DBA_HIST_ACTIVE_SESS_HISTORY TO INSTANAROLE;
GRANT SELECT ON DBA_USERS TO INSTANAROLE;
GRANT SELECT ON DBA_OBJECTS TO INSTANAROLE;
GRANT SELECT ON DBA_TABLESPACE_USAGE_METRICS TO INSTANAROLE;
GRANT SELECT ON DBA_DATA_FILES TO INSTANAROLE;
GRANT SELECT ON DBA_TEMP_FILES TO INSTANAROLE;
GRANT SELECT ON V_$LOG TO INSTANAROLE;
GRANT SELECT ON DBA_FREE_SPACE TO INSTANAROLE;

-- Assign Instana role to otelu user
GRANT INSTANAROLE TO otelu;

-- Commit role assignments
COMMIT;

-- Note: The following tables/views require the Oracle Diagnostic Pack license:
-- V$ACTIVE_SESSION_HISTORY, DBA_HIST_SNAPSHOT, DBA_HIST_SQLSTAT, DBA_HIST_SQLTEXT, DBA_HIST_ACTIVE_SESS_HISTORY

-- Accounting Service: create tables (Oracle doesn't use schemas the same way as PostgreSQL)
-- Tables are created in the user's schema
CREATE TABLE otelu."order" (
    order_id VARCHAR2(4000) PRIMARY KEY
);

CREATE TABLE otelu.shipping (
    shipping_tracking_id VARCHAR2(4000) PRIMARY KEY,
    shipping_cost_currency_code VARCHAR2(4000) NOT NULL,
    shipping_cost_units NUMBER(19) NOT NULL,
    shipping_cost_nanos NUMBER(10) NOT NULL,
    street_address VARCHAR2(4000),
    city VARCHAR2(4000),
    state VARCHAR2(4000),
    country VARCHAR2(4000),
    zip_code VARCHAR2(4000),
    order_id VARCHAR2(4000) NOT NULL,
    CONSTRAINT fk_shipping_order FOREIGN KEY (order_id) REFERENCES otelu."order"(order_id) ON DELETE CASCADE
);

CREATE TABLE otelu.orderitem (
    item_cost_currency_code VARCHAR2(4000) NOT NULL,
    item_cost_units NUMBER(19) NOT NULL,
    item_cost_nanos NUMBER(10) NOT NULL,
    product_id VARCHAR2(4000) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    order_id VARCHAR2(4000) NOT NULL,
    PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id) REFERENCES otelu."order"(order_id) ON DELETE CASCADE
);

-- Product Review Service
CREATE TABLE otelu.productreviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR2(16) NOT NULL,
    username VARCHAR2(64) NOT NULL,
    description VARCHAR2(1024),
    score NUMBER(3,1) NOT NULL
);

-- Product Review Service: create index for product_id lookups (ignore if exists)
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX product_id_index ON otelu.productreviews (product_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            NULL; -- Index already exists, ignore
        ELSE
            RAISE;
        END IF;
END;
/

-- Product Review Service: add product review data (only if table is empty)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM otelu.productreviews;
    IF v_count = 0 THEN
        INSERT ALL
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('OLJCESPC7Z', 'stargazer_mike', 'Great entry-level telescope! Easy to set up and provides clear views of the moon and brighter planets. Highly recommend for new astronomers.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('OLJCESPC7Z', 'nightskylover', 'For the price, this Explorascope delivers excellent performance. I was able to see Jupiter''s moons clearly. A fantastic purchase for casual viewing.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('OLJCESPC7Z', 'beginner_astro', 'A bit tricky to get used to the manual controls, but once you do, it''s very rewarding. Saw the Orion Nebula for the first time! Good value.', 3.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('OLJCESPC7Z', 'celestial_explorer', 'Perfect for camping trips. It''s lightweight and portable, making it easy to take anywhere. The views are surprisingly good for its size.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('OLJCESPC7Z', 'telescope_fan', 'Not the most powerful scope, but it''s great for kids and beginners. My children love looking at the moon with it. A solid choice for family fun.', 3.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('66VCHSJNUP', 'tech_astro', 'The StarSense app is revolutionary! It made finding celestial objects incredibly easy. This telescope is a game-changer for beginners.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('66VCHSJNUP', 'app_user', 'Amazing technology, the smartphone integration works flawlessly. I''ve never had so much fun exploring the night sky. Worth every penny.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('66VCHSJNUP', 'innovator_john', 'Setup was a breeze, and the tutorials in the app are very helpful. The views are crisp and clear. My only minor gripe is battery drain on the phone.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('66VCHSJNUP', 'clear_skies', 'Finally, a telescope that takes the guesswork out of stargazing. The real-time positioning is incredibly accurate. Highly recommended for anyone new to astronomy.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('66VCHSJNUP', 'gadget_geek', 'Fantastic product, the app truly guides you. It''s like having a personal astronomer with you. The optical quality is also very good.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('1YMWWN1N4O', 'solar_viewer', 'Perfect for solar observations! The Solar Safe filter gives peace of mind. I used it for the last partial eclipse and it was fantastic.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('1YMWWN1N4O', 'eclipse_chaser', 'Compact and easy to carry, this telescope is ideal for eclipse events. The included backpack is a nice touch. Views of the sun are incredibly clear and safe.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('1YMWWN1N4O', 'travel_astro', 'Excellent travel scope for solar viewing. The magnification is much better than binoculars for the sun. A must-have for any solar enthusiast.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('1YMWWN1N4O', 'sun_gazer', 'Very impressed with the safety features and clarity. Sharing the sun with family has never been easier or safer. Great value for a dedicated solar scope.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('1YMWWN1N4O', 'safe_viewer', 'The ISO compliant filter is reassuring. It''s a well-designed product for safe solar observation. Highly recommend for educational purposes too.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('L9ECAV7KIM', 'clean_optics', 'This kit is a lifesaver for all my optics. The brush and wipes work perfectly without leaving any residue. My lenses have never been cleaner.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('L9ECAV7KIM', 'photog_pro', 'Essential for any photographer or telescope owner. It safely removes dust and fingerprints. A high-quality cleaning solution.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('L9ECAV7KIM', 'daily_cleaner', 'I use this on my binoculars, camera lenses, and even my phone screen. It''s very effective and gentle. A versatile cleaning kit.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('L9ECAV7KIM', 'tech_maintenance', 'Great value for money. The different cleaning options cover all needs. Keeps my expensive equipment in pristine condition.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('L9ECAV7KIM', 'sharp_view', 'Works as advertised, my telescope views are much clearer after using this. The fluid and cloth are excellent. Definitely recommend.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('2ZYFJ3GM2N', 'bird_watcher', 'Incredible clarity and brightness, perfect for bird watching. The ED glass really makes a difference. I can spot the subtlest markings.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('2ZYFJ3GM2N', 'nature_lover', 'These binoculars are fantastic for nature observation. The close focus is a huge advantage for viewing nearby wildlife. Very comfortable to hold.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('2ZYFJ3GM2N', 'hiker_guy', 'Lightweight and durable, these are my go-to binoculars for hiking. The wide field of view is excellent. Highly recommend for outdoor enthusiasts.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('2ZYFJ3GM2N', 'stadium_fan', 'Took these to a game and had an amazing view of the action. They perform great in various lighting conditions. A solid all-around binocular.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('2ZYFJ3GM2N', 'outdoor_adventurer', 'Excellent build quality and optical performance. They feel robust and provide sharp images. A great investment for any outdoor activity.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('0PUK6V6EV0', 'astro_photog', 'This imager is a fantastic step up for planetary photography. The color quality is superb. Easy to use with my existing telescope setup.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('0PUK6V6EV0', 'planet_shooter', 'Finally capturing stunning images of Saturn and Jupiter! The NexImage 10 makes it so accessible. Great for beginners in astrophotography.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('0PUK6V6EV0', 'imager_pro', 'Excellent resolution and color rendition for its price point. It''s a perfect solution for those looking to start imaging planets. Highly satisfied.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('0PUK6V6EV0', 'space_artist', 'The detail I can capture with this imager is incredible. It integrates well with various software. A must-have for serious planetary observers.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('0PUK6V6EV0', 'digital_sky', 'A solid choice for getting into solar system imaging. The setup was straightforward. Produces beautiful, vibrant planetary images.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('LS4PSXUNUM', 'night_walker', 'The red light is perfect for preserving night vision during astronomy sessions. The hand warmer is an unexpected bonus. Very practical device.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('LS4PSXUNUM', 'star_party_goer', 'This flashlight is indispensable for star parties. The red mode is gentle on the eyes, and the power bank feature is super handy. Love it!', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('LS4PSXUNUM', 'camper_chris', 'Rugged and versatile, this flashlight is great for camping and night walks. The hand warmer function is a game-changer on cold nights. Highly recommend.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('LS4PSXUNUM', 'emergency_kit', 'A fantastic multi-tool for my emergency kit. The red light is useful, and the power bank means I can charge my phone. Great design.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('LS4PSXUNUM', 'astro_accessory', 'Every astronomer needs one of these. The red light is essential, and the hand warmer and power bank make it incredibly useful. A top-tier accessory.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('9SIQT8TOJO', 'deep_sky_master', 'The RASA V2 is a dream come true for deep-sky imaging. The f/2.2 speed drastically cuts down exposure times. My best astrophotography investment yet.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('9SIQT8TOJO', 'pro_astro', 'Unbelievable performance for wide-field astrophotography. The short focal length makes guiding less critical. Produces stunning, detailed images.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('9SIQT8TOJO', 'imaging_guru', 'This OTA is a beast! The fast optics mean more data in less time. If you''re serious about deep-sky imaging, this is the one.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('9SIQT8TOJO', 'advanced_scope', 'Worth every penny for the quality and speed it offers. My images have never been sharper or more vibrant. A truly professional piece of equipment.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('9SIQT8TOJO', 'precision_optics', 'The engineering behind this RASA is exceptional. It''s incredibly efficient for capturing faint objects. A high-end choice for dedicated imagers.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('6E92ZMYYFZ', 'solar_safety', 'Essential for safe solar viewing with my 8-inch telescope. The Velcro straps ensure it stays securely in place. Peace of mind during solar observations.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('6E92ZMYYFZ', 'telescope_upgrade', 'This EclipSmart filter is a perfect addition to my setup. The ISO compliance is crucial. Highly recommend for anyone looking to view the sun safely.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('6E92ZMYYFZ', 'safe_sun_gazer', 'Easy to attach and provides crystal clear, safe views of the sun. The build quality is excellent. A must-have accessory for solar enthusiasts.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('6E92ZMYYFZ', 'filter_fan', 'Works perfectly with my 8-inch scope. No more worries about accidental dislodgement. Great product for protecting your eyes and equipment.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('6E92ZMYYFZ', 'eclipse_ready', 'Bought this for the upcoming eclipse, and it fits perfectly. Tested it out, and the views are fantastic and safe. Very happy with this purchase.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('HQTGWGPNH4', 'history_buff', 'A fascinating glimpse into historical astronomical thought. The content is incredibly insightful. A must-read for anyone interested in the history of science.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('HQTGWGPNH4', 'bookworm_astro', 'Beautifully presented historical document. It''s amazing to see how comets were understood centuries ago. A valuable addition to any astronomy library.', 4.5)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('HQTGWGPNH4', 'ancient_texts', 'Such a unique and intriguing read. The historical context is captivating. It offers a different perspective on celestial events.', 4.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('HQTGWGPNH4', 'celestial_history', 'I love historical astronomy, and this book delivers. It''s well-researched and provides a window into past beliefs. Highly recommended for scholars.', 5.0)
    INTO otelu.productreviews (product_id, username, description, score) VALUES ('HQTGWGPNH4', 'rare_find', 'A truly special book for enthusiasts of astronomical history. The details about ancient astrologers are very interesting. Great for a deeper understanding.', 4.5)
SELECT * FROM dual;
    END IF;
END;
/

-- Product Catalog Service: create tables
CREATE TABLE otelu.products (
    id VARCHAR2(4000) PRIMARY KEY,
    name VARCHAR2(4000) NOT NULL,
    description CLOB,
    picture VARCHAR2(4000),
    price_currency_code VARCHAR2(4000) NOT NULL,
    price_units NUMBER(19) NOT NULL,
    price_nanos NUMBER(10) NOT NULL,
    categories VARCHAR2(4000)
);

-- Product Catalog Service: add product data (only if table is empty)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM otelu.products;
    IF v_count = 0 THEN
        INSERT ALL
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('OLJCESPC7Z', 'National Park Foundation Explorascope', 'The National Park Foundation''s (NPF) Explorascope 60AZ is a manual alt-azimuth, refractor telescope perfect for celestial viewing on the go. The NPF Explorascope 60 can view the planets, moon, star clusters and brighter deep sky objects like the Orion Nebula and Andromeda Galaxy.', 'NationalParkFoundationExplorascope.jpg', 'USD', 101, 960000000, 'telescopes')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('66VCHSJNUP', 'Starsense Explorer Refractor Telescope', 'The first telescope that uses your smartphone to analyze the night sky and calculate its position in real time. StarSense Explorer is ideal for beginners thanks to the app''s user-friendly interface and detailed tutorials. It''s like having your own personal tour guide of the night sky', 'StarsenseExplorer.jpg', 'USD', 349, 950000000, 'telescopes')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('1YMWWN1N4O', 'Eclipsmart Travel Refractor Telescope', 'Dedicated white-light solar scope for the observer on the go. The 50mm refracting solar scope uses Solar Safe, ISO compliant, full-aperture glass filter material to ensure the safest view of solar events.  The kit comes complete with everything you need, including the dedicated travel solar scope, a Solar Safe finderscope, tripod, a high quality 20mm (18x) Kellner eyepiece and a nylon backpack to carry everything in.  This Travel Solar Scope makes it easy to share the Sun as well as partial and total solar eclipses with the whole family and offers much higher magnifications than you would otherwise get using handheld solar viewers or binoculars.', 'EclipsmartTravelRefractorTelescope.jpg', 'USD', 129, 950000000, 'telescopes,travel')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('L9ECAV7KIM', 'Lens Cleaning Kit', 'Wipe away dust, dirt, fingerprints and other particles on your lenses to see clearly with the Lens Cleaning Kit. This cleaning kit works on all glass and optical surfaces, including telescopes, binoculars, spotting scopes, monoculars, microscopes, and even your camera lenses, computer screens, and mobile devices.  The kit comes complete with a retractable lens brush to remove dust particles and dirt and two options to clean smudges and fingerprints off of your optics, pre-moistened lens wipes and a bottled lens cleaning fluid with soft cloth.', 'LensCleaningKit.jpg', 'USD', 21, 950000000, 'accessories')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('2ZYFJ3GM2N', 'Roof Binoculars', 'This versatile, all-around binocular is a great choice for the trail, the stadium, the arena, or just about anywhere you want a close-up view of the action without sacrificing brightness or detail. It''s an especially great companion for nature observation and bird watching, with ED glass that helps you spot the subtlest field markings and a close focus of just 6.5 feet.', 'RoofBinoculars.jpg', 'USD', 209, 950000000, 'binoculars')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('0PUK6V6EV0', 'Solar System Color Imager', 'You have your new telescope and have observed Saturn and Jupiter. Now you''re ready to take the next step and start imaging them. But where do you begin? The NexImage 10 Solar System Imager is the perfect solution.', 'SolarSystemColorImager.jpg', 'USD', 175, 0, 'accessories,telescopes')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('LS4PSXUNUM', 'Red Flashlight', 'This 3-in-1 device features a 3-mode red flashlight, a hand warmer, and a portable power bank for recharging your personal electronics on the go. Whether you use it to light the way at an astronomy star party, a night walk, or wildlife research, ThermoTorch 3 Astro Red''s rugged, IPX4-rated design will withstand your everyday activities.', 'RedFlashlight.jpg', 'USD', 57, 80000000, 'accessories,flashlights')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('9SIQT8TOJO', 'Optical Tube Assembly', 'Capturing impressive deep-sky astroimages is easier than ever with Rowe-Ackermann Schmidt Astrograph (RASA) V2, the perfect companion to today''s top DSLR or astronomical CCD cameras. This fast, wide-field f/2.2 system allows for shorter exposure times compared to traditional f/10 astroimaging, without sacrificing resolution. Because shorter sub-exposure times are possible, your equatorial mount won''t need to accurately track over extended periods. The short focal length also lessens equatorial tracking demands. In many cases, autoguiding will not be required.', 'OpticalTubeAssembly.jpg', 'USD', 3599, 0, 'accessories,telescopes,assembly')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('6E92ZMYYFZ', 'Solar Filter', 'Enhance your viewing experience with EclipSmart Solar Filter for 8" telescopes. With two Velcro straps and four self-adhesive Velcro pads for added safety, you can be assured that the solar filter cannot be accidentally knocked off and will provide Solar Safe, ISO compliant viewing.', 'SolarFilter.jpg', 'USD', 69, 950000000, 'accessories,telescopes')
    INTO otelu.products (id, name, description, picture, price_currency_code, price_units, price_nanos, categories) VALUES ('HQTGWGPNH4', 'The Comet Book', 'A 16th-century treatise on comets, created anonymously in Flanders (now northern France) and now held at the Universitätsbibliothek Kassel. Commonly known as The Comet Book (or Kometenbuch in German), its full title translates as "Comets and their General and Particular Meanings, According to Ptolomeé, Albumasar, Haly, Aliquind and other Astrologers". The image is from https://publicdomainreview.org/collection/the-comet-book, made available by the Universitätsbibliothek Kassel under a CC-BY SA 4.0 license (https://creativecommons.org/licenses/by-sa/4.0/)', 'TheCometBook.jpg', 'USD', 0, 990000000, 'books')
SELECT * FROM dual;
    END IF;
END;
/

COMMIT;
